
sudo: false

before_install:
  - docker-compose up -d
  - sleep 10

before_script:
  - mysql -h 127.0.0.1 -e 'create database search_cop;'
  - psql -h 127.0.0.1 -c "create user search_cop password 'secret';" -U postgres
  - psql -h 127.0.0.1 -c 'create database search_cop owner search_cop;' -U postgres

matrix:
  include:
    - rvm: ruby-2.6.6
      gemfile: gemfiles/5.1.gemfile
      env: DATABASE=sqlite
    - rvm: ruby-2.6.6
      gemfile: gemfiles/5.1.gemfile
      env: DATABASE=mysql
    - rvm: ruby-2.6.6
      gemfile: gemfiles/5.1.gemfile
      env: DATABASE=postgres
    - rvm: ruby-head
      gemfile: gemfiles/6.0.gemfile
      env: DATABASE=sqlite
    - rvm: ruby-head
      gemfile: gemfiles/6.0.gemfile
      env: DATABASE=mysql
    - rvm: ruby-head
      gemfile: gemfiles/6.0.gemfile
      env: DATABASE=postgres

install:
  - "travis_retry bundle install"

script:
  - rake test --trace
  - rubocop

