
addons:
  postgresql: "9.6"

before_script:
  - mysql -e 'create database search_cop;'
  - psql -c "create user search_cop password 'secret';" -U postgres
  - psql -c 'create database search_cop owner search_cop;' -U postgres

rvm:
  - ruby-head
  - jruby
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres
matrix:
  allow_failures:
    - rvm: jruby

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

install:
  - "travis_retry bundle install"

script: "rake test"
sudo: false

