
version: '2' 
services:
  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 3306:3306
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: search_cop
      POSTGRES_USER: search_cop
      POSTGRES_PASSWORD: secret
      DB_HSTORE: "true"
    ports:
      - 5432:5432
