name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7"]
        rails: ["5.1", "6.0"]
        database: ["sqlite", "postgres", "mysql"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: search_cop
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: search_cop
        ports:
          - 5432:5432
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: search_cop
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - env:
          DATABASE: ${{ matrix.database }}
        run: |
          gem install bundler
          bundle install --gemfile=gemfiles/${{ matrix.rails }}.gemfile --path=vendor/bundler
          bundle exec --gemfile=gemfiles/${{ matrix.rails }}.gemfile rspec
          bundle exec --gemfile=gemfiles/${{ matrix.rails }}.gemfile rubocop
